### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by p2004a** [stefano/pyduktape#4]
Unfortunately, it looks like this library doesn't support python3:

```python
import pyduktape
pyduktape.DuktapeContext().eval_js('1+2;')
```

results in

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyduktape.pyx", line 197, in pyduktape.DuktapeContext.eval_js (pyduktape.c:2925)
  File "pyduktape.pyx", line 220, in pyduktape.DuktapeContext._eval_js (pyduktape.c:3656)
  File "pyduktape.pyx", line 195, in pyduktape.DuktapeContext.eval_js.eval_string (pyduktape.c:2795)
TypeError: expected bytes, str found
```

**Comment by huubbouma** [comment]
I'm facing the same issue now. I would love to have python3 supported!

**Comment by stefano** [comment]
6 months late, but python 3 support is here! Let me know if you find anything that works on python 2 but not on python 3.
